# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc79dd81f9583f1899e9daf4eab8f459121c4b69de15c98042c5790285f0ad85e3d793e215f67d804e627760bde9d4e41f77205de0276699e2d9cb8882181c00

test:
  secret_key_base: e75cf65c3a0b8c54484e9fafa0b2ca5d8e09837c9e8450e576b2dba813c7ba6443bf534482665195879ae26b917ccd9835ca852ad42bc055ea5935514ff3e7de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
